### ISSUE TITLE
Silent Failure when calling task from another task

### ISSUE THREAD

**Issue by mscanlon-exos** [PrefectHQ/prefect-slack#43]
I'm not too sure what the intended behavior here would be, but in prefect 1 we had written a custom library for sending slack notifications during prefect tasks. The logic of this library is strikingly similar to that of the underlying logic for functions like `send_chat_message` which makes me wonder why `send_chat_message.fn()` would silently fail inside of a flow's task. 

If i have a flow and task
```
@task
def foo():
    send_chat_message.fn(SlackCredentials.load('token'), '#myChannel', 'Some text to send')
    
@flow
def bar():
    foo()
```

The task is triggered, the flow succeeds, but you won't see the message sent to `#myChannel`

Is this expected behavior? If so why?

**Comment by ahuang11** [comment]
Hi @mscanlon-exos, apologies for the late reply.

I received this warning when running this:
```
RuntimeWarning: coroutine 'send_incoming_webhook_message' was never awaited
  send_incoming_webhook_message.fn(
```

That makes sense because the underlying task's function is async.

As a task, the Prefect engine can handle this in async/sync flows.

However, once `fn` is called, it's reverted to a basic Python async function.

Can you elaborate on your use-case for using `fn`?

**Comment by ahuang11** [comment]
Closing this for now. Let me know if you still encounter this!
